/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CharactersIndexRouteImport } from './routes/characters.index'
import { Route as CharactersIdRouteImport } from './routes/characters.$id'
import { Route as WeaponsIndexRouteImport } from './routes/weapons.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CharactersIndexRoute = CharactersIndexRouteImport.update({
  id: '/characters/',
  path: '/characters/',
  getParentRoute: () => rootRouteImport,
} as any)
const CharactersIdRoute = CharactersIdRouteImport.update({
  id: '/characters/$id',
  path: '/characters/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const WeaponsIndexRoute = WeaponsIndexRouteImport.update({
  id: '/weapons/',
  path: '/weapons/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/characters/$id': typeof CharactersIdRoute
  '/characters/': typeof CharactersIndexRoute
  '/weapons/': typeof WeaponsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/characters/$id': typeof CharactersIdRoute
  '/characters': typeof CharactersIndexRoute
  '/weapons': typeof WeaponsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/characters/$id': typeof CharactersIdRoute
  '/characters/': typeof CharactersIndexRoute
  '/weapons/': typeof WeaponsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/characters/$id' | '/characters/' | '/weapons/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/characters/$id' | '/characters' | '/weapons'
  id: '__root__' | '/' | '/characters/$id' | '/characters/' | '/weapons/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CharactersIdRoute: typeof CharactersIdRoute
  CharactersIndexRoute: typeof CharactersIndexRoute
  WeaponsIndexRoute: typeof WeaponsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/characters/': {
      id: '/characters/'
      path: '/characters'
      fullPath: '/characters/'
      preLoaderRoute: typeof CharactersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/characters/$id': {
      id: '/characters/$id'
      path: '/characters/$id'
      fullPath: '/characters/$id'
      preLoaderRoute: typeof CharactersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/weapons/': {
      id: '/weapons/'
      path: '/weapons'
      fullPath: '/weapons/'
      preLoaderRoute: typeof WeaponsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CharactersIdRoute: CharactersIdRoute,
  CharactersIndexRoute: CharactersIndexRoute,
  WeaponsIndexRoute: WeaponsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
